spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://fitness-sarimxahid123-7a0a.e.aivencloud.com:25643/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_uDdVbubU2Lv_x4DPVre
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/